# Inner Makefile: used inside the Docker container.
# Only depends on zcc (from z88dk).

PROJECT = app
SRCS = src/main.c src/game.c src/render.c src/input.c src/sound.c src/level.c src/loading_scr.c src/assets_gfx.c
CFLAGS = +zx -vn -SO3 -clib=new -pragma-include:zpragma.inc -m
LDFLAGS = -create-app

all: build/$(PROJECT).tap

build/$(PROJECT).tap: $(SRCS) zpragma.inc
	@mkdir -p build
	zcc $(CFLAGS) $(SRCS) -o build/$(PROJECT) $(LDFLAGS)

clean:
	rm -rf build/

.PHONY: all clean
