/* generated -- do not edit by hand */
/* generated by tools/png2zx.py --gfx */
#ifndef ASSETS_GFX_H
#define ASSETS_GFX_H

#include <stdint.h>

extern const uint8_t gfx_floor[8];
extern const uint8_t gfx_wall[8];
extern const uint8_t gfx_pad[8];
extern const uint8_t gfx_entry[8];
extern const uint8_t gfx_core[8];
extern const uint8_t gfx_turret_laser[8];
extern const uint8_t gfx_turret_missile[8];
extern const uint8_t gfx_turret_tesla[8];
extern const uint8_t gfx_enemy_drone[8];
extern const uint8_t gfx_enemy_runner[8];
extern const uint8_t gfx_enemy_brute[8];

#endif /* ASSETS_GFX_H */
